### ISSUE TITLE
Current build fails due to 'libc6:i386' configuration issue

### ISSUE THREAD

**Issue by adworacz** [mviereck/dockerfile-x11docker-xfce-wine-playonlinux#9]
Hello! Thank you for your wonderful project by the way! It's made my life much easier!

I'm currently attempting to build the Dockerfile locally (using `podman`), and I'm receiving the following error (note: I did disable `playonlinux` installation as I won't be using it, but that doesn't appear to be the issue here):

```
Processing triggers for wine (5.0.3-3) ...
Processing triggers for libc-bin (2.31-4) ...
Processing triggers for libgdk-pixbuf-2.0-0:i386 (2.42.2+dfsg-1) ...
E: Could not configure 'libc6:i386'.
W: Could not perform immediate configuration on 'libgcc-s1:i386'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
Error: error building at STEP "RUN echo "deb http://deb.debian.org/debian buster contrib" >> /etc/apt/sources.list &&     env DEBIAN_FRONTEND=noninteractive dpkg --add-architecture i386 &&     apt-get update &&     env DEBIAN_FRONTEND=noninteractive apt-get install -y       fonts-wine       locales       ttf-mscorefonts-installer       wget       winbind       winetricks &&     mkdir -p /usr/share/wine/gecko &&     cd /usr/share/wine/gecko &&       wget https://dl.winehq.org/wine/wine-gecko/2.47/wine_gecko-2.47-x86.msi &&       wget https://dl.winehq.org/wine/wine-gecko/2.47/wine_gecko-2.47-x86_64.msi &&     mkdir -p /usr/share/wine/mono &&     cd /usr/share/wine/mono &&       wget https://dl.winehq.org/wine/wine-mono/4.7.1/wine-mono-4.7.1.msi &&     env DEBIAN_FRONTEND=noninteractive apt-get install -y       gettext       gnome-icon-theme       q4wine       xterm &&     env DEBIAN_FRONTEND=noninteractive apt-get install -y       libxv1       mesa-utils       mesa-utils-extra &&     env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends       libpulse0       pavucontrol       pasystray": error while running runtime: exit status 100
```

Seems to be some kind of issue with the 32 bit binaries on Debian. Unfortunately, my knowledge is pretty limited here.

**Comment by adworacz** [comment]
Actually, figured out the issue - I was building this image directly, but not it's parent of the `x11docker/xfce` image, which was pulling down a really old version of Debian by default. 

I'm now building all packages, including the xserver (Nvidia), xfce, and this, and it all works just fine now.

Sorry for the bother!

**Comment by mviereck** [comment]
Thank you for the report and also posting your solution!
Great to hear that this project is pretty useful for you.

**Comment by mviereck** [comment]
I had a look at the Dockerfile and found a minor bug:
The image builds upon x11docker/xfce that in turn is based on Debian bullseye.
But the Dockerfile added a sources.list contrib entry pointing to previous Debian buster.
This affects mainly `playonlinux` and has no major impact. 
However, it is fixed now and I want to let you know.

wine gecko and wine mono versions were also wrong; I've updated the Dockerfile to versions matching the installed wine version.

**Comment by adworacz** [comment]
Awesome, thank you for the updates!
